GET http://localhost:3000/products#index

###

GET http://localhost:3000/products

###

GET http://localhost:3000/products/3

###

POST http://localhost:3000/products
content-type: application/json

{
  "input_name": "Tricone",
  "input_price": 5655,
  "input_url": "mrmrmrmr.com",
  "input_description": "a Tricone"
}

###
PATCH http://localhost:3000/products/3
content-type: application/json

{
  "input_name": "National Tricone Style 1 Resonator",
  "input_price": 6750,
  "input_url": "https://www.12fret.com/wp-content/uploads/ngg_featured/national-style-1-tricone-2001-cons-full-front.jpg",
  "input_description": "A reproduction of the 1927 classic Style 1 Tricone resonator guitar by National Guitars"
  }

###

POST http://localhost:3000/products
content-type: application/json

{
  "input_name": "test destroy",
  "input_price": 5655,
  "input_url": "destroythis.com",
  "input_description": "only destruction here"
}

###

DELETE http://localhost:3000/products/4