GET http://localhost:3000/products#index

###

GET http://localhost:3000/products

###

GET http://localhost:3000/products/1

###

POST http://localhost:3000/products
content-type: application/json

{
  "input_name": "Tricone",
  "input_price": 5655,
  "input_url": "mrmrmrmr.com",
  "input_description": "a Tricone"
}

###
PATCH http://localhost:3000/products/1
content-type: application/json

